version: 1.1.1.{build}
image: Visual Studio 2019
CONFIGURATION:
- Release
- Debug

environment:
  matrix:
    - GENERATOR: Visual Studio 16 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: Win32
      
    - GENERATOR: Visual Studio 16 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: x64
      
init:
- cmake --version
install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- vcpkg install fmt:x86-windows
- vcpkg install fmt:x64-windows
- vcpkg integrate install
- cd %APPVEYOR_BUILD_FOLDER%

before_build:
- md build
- cd build
- cmake --config "%CONFIGURATION%" -G "%GENERATOR%"  -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
build_script:
- cmake --build . --config "%CONFIGURATION%"
build:
  verbosity: minimal

cache:
- C:\Tools\vcpkg\installed\